#!/bin/bash
#
# Create a new Nginx virtual host
#
# https://maicong.me/2015-09-15-mc-lnmp.html
#
# Usage: service vhost (start,stop,list,add,edit,del,exit) <domain> <server_name> <index_name> <rewrite_file> <host_subdirectory>

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

# Sanity check
[ $(id -g) != "0" ] && die "Script must be run as root.";

if [ "$*" != '' ]; then
    selected=$1;
    domain=$2;
    server_name=$3;
    index_name=$4;
    rewrite_file=$5;
    host_subdirectory=$6;
else
    echo "Host Management please select: (1~7)"
    select selected in 'start' 'stop' 'list' 'add' 'edit' 'del' 'exit'; do
        break;
    done;
fi;

www_root=/home/wwwroot;
php_fpm_BIN=/usr/sbin/php-fpm;
nginx_BIN=/usr/sbin/nginx;
nginx_CONF=/etc/nginx/nginx.conf;
nginx_EDIR=/etc/nginx/conf.d;
nginx_SDIR=/etc/nginx/conf.d.stop;
nginx_PID=/var/run/nginx.pid;

if [ "$domain" != '' ]; then
    php_fpm_ECONF=/etc/php-fpm.d/php-$domain.conf;
    php_fpm_SCONF=/etc/php-fpm.d.stop/php-$domain.conf;
    php_fpm_PID=/run/php-fpm/php-fpm-$domain.pid;
    nginx_ECONF=$nginx_EDIR/nginx-$domain.conf;
    nginx_SCONF=$nginx_SDIR/nginx-$domain.conf; 
fi;

if [ "$selected" == 'list' ]; then

    for line in `ls $www_root/`; do
        [ -f "$nginx_EDIR/nginx-$line.conf" ] && echo $line [Running];
        [ -f "$nginx_SDIR/nginx-$line.conf" ] && echo $line [Stop];
    done;

elif [ "$selected" == 'add' ]; then

    if [ "$domain" == '' ]; then
        read -p "[Notice] Please input domain: " domain;
        [ "$domain" == '' ] && echo '[error] empty domain' && exit 1;
        service vhost add $domain;
        exit 0;
    fi;

    if [ "$server_name" == '' ]; then
        read -p "[Notice] Please input server name (e.g: domain.com,www.domain.com): " server_name;
        [ "$server_name" == '' ] && echo "[error] empty server name" && exit 1;
        service vhost add $domain $server_name;
        exit 0;
    fi;

    [ -f $nginx_ECONF ] || [ -f $nginx_SCONF ] && echo "[Error] $domain is exist!" && exit 1;

    # nginx-host.conf
    [ -d /etc/php-fpm.d ] && sock=php-fpm-$domain.sock || sock=php-fpm.sock;
    cp /etc/nginx/nginx-host.conf $nginx_ECONF;

    sed -i "s#example#$domain#g" $nginx_ECONF;
    sed -i "s#php-fpm.sock#$sock#g" $nginx_ECONF;

    [ "$server_name" != '' ] && [ "$server_name" != '0' ] && server_name=${server_name//,/ } && \
    sed -i "s|server_name .* #server_name end|server_name $server_name; #server_name end|" $nginx_ECONF;

    [ "$index_name" != '' ] && [ "$index_name" != '0' ] && index_name=${index_name//,/ } && \
    sed -i "s|index .* #index end|index $index_name; #index end|" $nginx_ECONF;

    [ "$rewrite_file" != '' ] && [ "$rewrite_file" != '0' ] && \
    sed -i "s|include rewrite/.*; #rewrite end|include rewrite/$rewrite_file; #rewrite end|" $nginx_ECONF;

    sed -i "/set \$subdomain \"\/\$2\"/d" $nginx_ECONF;
    [ "$host_subdirectory" == 'on' ] && sed -i "/set \$subdomain/a\ \tif ( \$host ~* \"(?:(\\\w+\\\.){0,})(\\\b(?\!www\\\b)\\\w+)\\\.\\\b(?\!(com|org|gov|net|cn)\\\b)\\\w+\\\.\[a-zA-Z\]+\" ) { set \$subdomain \"\/\$2\"; }" $nginx_ECONF;

    # php-fpm
    if [ -d /etc/php-fpm.d ];then
        cp /etc/php-fpm-host.conf $php_fpm_ECONF;
        sed -i "s#example#$domain#g" $php_fpm_ECONF;
    fi;

    # wwwroot chroot
    mkdir -p $www_root/$domain;
    touch $www_root/$domain/index.html;
    echo 'Welcome!' > $www_root/$domain/index.html;

    if [ -f $nginx_PID ]; then
        kill -HUP `cat $nginx_PID`;
    else
        $nginx_BIN -c $nginx_CONF;
    fi;

    $php_fpm_BIN --daemonize --fpm-config $php_fpm_ECONF --pid $php_fpm_PID;
    echo "[OK] successfully create $domain vhost";
    echo "The DocumentRoot: $www_root/$domain/";

    exit;

elif [ "$selected" == 'edit' ]; then

    [ "$domain" == '' ] && read -p "[Notice] Please input domain:" domain
    [ "$domain" == '' ] && echo '[error] empty domain' && exit 1;

    [ ! -f $nginx_ECONF ] && [ ! -f $nginx_SCONF ] && echo "[Error] $domain not exist!" && exit 1;
    [ -f $nginx_ECONF ] && host_conf_file=$nginx_ECONF || host_conf_file=$nginx_SCONF;

    [ "$server_name" == '' ] && read -p "[Notice] Please input server name (e.g: domain.com,www.domain.com). cancel edit, please input 0 : " server_name;

    [ "$index_name" == '' ] && read -p "[Notice] Please input Nginx-index file name (e.g: index.html,index.htm,index.php). cancel edit, please input 0 : " index_name;

    [ "$rewrite_file" == '' ] && read -p "[Notice] Please input Nginx-rewrite file name (e.g: nomal.conf). cancel edit, please input 0 : " rewrite_file;

    [ "$host_subdirectory" == '' ] && read -p "[Notice] Binding second-level domain? please input on OR off. cancel edit, please input 0 : " host_subdirectory;

    # nginx-host.conf
    [ "$server_name" != '' ] && [ "$server_name" != '0' ] && server_name=${server_name//,/ } && \
    sed -i "s|server_name .* #server_name end|server_name $server_name; #server_name end|" $host_conf_file;

    [ "$index_name" != '' ] && [ "$index_name" != '0' ] && index_name=${index_name//,/ } && \
    sed -i "s|index .* #index end|index $index_name; #index end|" $host_conf_file;

    [ "$rewrite_file" != '' ] && [ "$rewrite_file" != '0' ] && \
    sed -i "s|include rewrite/.*; #rewrite end|include rewrite/$rewrite_file; #rewrite end|" $host_conf_file;

    sed -i "/set \$subdomain \"\/\$2\"/d" $host_conf_file;
    [ "$host_subdirectory" == 'on' ] && sed -i "/set \$subdomain/a\ \tif ( \$host ~* \"(?:(\\\w+\\\.){0,})(\\\b(?\!www\\\b)\\\w+)\\\.\\\b(?\!(com|org|gov|net|cn)\\\b)\\\w+\\\.\[a-zA-Z\]+\" ) { set \$subdomain \"\/\$2\"; }" $host_conf_file;

    kill -HUP `cat /var/run/nginx.pid`;
    kill -QUIT `cat /run/php-fpm/php-fpm-$domain.pid`;
    /usr/sbin/php-fpm --fpm-config /etc/php-fpm.d/php-$domain.conf;
    echo "[OK] successfully change $domain vhost";

    exit;

elif [ "$selected" == 'start' ]; then

    if [ "$domain" == '' ]; then
        echo "[Notice] All host start...";
        for line in `ls $www_root/`; do
            if [ -f "$nginx_SDIR/nginx-$line.conf" ]; then
                service vhost start $line;
            else
                echo "[ERROR] $line host maybe running or not exist";
            fi;
        done;
        exit 0;
    fi;

    # php
    if [ -f $php_fpm_PID ]; then
        echo "[ERROR] $domain vhost php-fpm already running";
    else
        [ -f $php_fpm_SCONF ] && mv -f $php_fpm_SCONF $php_fpm_ECONF;
        [ -f $php_fpm_ECONF ] && $php_fpm_BIN --daemonize --fpm-config $php_fpm_ECONF --pid $php_fpm_PID;
        [ -f $php_fpm_PID ] && echo "[OK] successfully start $domain vhost php-fpm";
    fi;

    # nginx
    if [ -f $nginx_PID ]; then
        echo "[ERROR] $domain vhost nginx already running";
    else
        [ -f $nginx_SCONF ] && mv -f $nginx_SCONF $nginx_ECONF;
        [ -f $nginx_ECONF ] && $nginx_BIN -c $nginx_CONF;
        [ -f $nginx_PID ] && echo "[OK] successfully start $domain vhost nginx";
    fi;

    exit;

elif [ "$selected" == 'stop' ]; then

    if [ "$domain" == '' ]; then
        echo "[Notice] All host stop...";
        for line in `ls $www_root/`; do
            if [ -f "$nginx_EDIR/nginx-$line.conf" ]; then
                service vhost stop $line;
            else
                echo "[ERROR] $line host maybe stopped or not exist";
            fi;
        done;
        exit 0;
    fi;

    # nginx
    if [ -f $nginx_PID ]; then
        [ -f $nginx_ECONF ] && mv -f $nginx_ECONF $nginx_SCONF;
        $nginx_BIN -s stop && echo "[OK] successfully stop $domain vhost nginx";
    else
        echo "[ERROR] $domain vhost nginx is not running";
    fi;

    # php
    if [ -f $php_fpm_PID ]; then
        [ -f $php_fpm_ECONF ] && mv -f $php_fpm_ECONF $php_fpm_SCONF;
        kill -QUIT `cat $php_fpm_PID` && echo "[OK] successfully stop $domain vhost php-fpm";
    else
        echo "[ERROR] $domain vhost php-fpm is not running";
    fi;

    exit;

elif [ "$selected" == 'del' ]; then

    if [ "$domain" == '' ]; then
        read -p "[Notice] deleted domain:" domain;
        [ "$domain" == '' ] && echo '[error] empty domain' && exit 1;
        service vhost del $domain;
        exit 0;
    fi;

    #nginx
    [ ! -f $nginx_ECONF ] && [ ! -f $nginx_SCONF ] && echo "[Error] $domain not exist!" && exit 1;
    [ -f $nginx_ECONF ] && rm -f $nginx_ECONF;
    [ -f $nginx_SCONF ] && rm -f $nginx_SCONF;
    [ -f $nginx_PID ] && $nginx_BIN -s stop && echo "[OK] successfully delete $domain vhost nginx";

    #php
    [ -f $php_fpm_ECONF ] && rm -f $php_fpm_ECONF;
    [ -f $php_fpm_SCONF ] && rm -f $php_fpm_SCONF;
    [ -f $php_fpm_PID ] && kill -QUIT `cat $php_fpm_PID` && echo "[OK] successfully delete $domain vhost php-fpm";

    #wwwroot
    read -p '[Notice] Delete the directory in wwwroot? (y/n) : ' confirmYN;
    [ "$confirmYN" != 'y' ] && exit;
    rm -rf $www_root/$domain && echo "[OK] successfully delete $domain vhost directory";
    
else
    exit;
fi;